from recbole.model.context_aware_recommender.afm import AFM
from recbole.model.context_aware_recommender.autoint import AutoInt
from recbole.model.context_aware_recommender.dcn import DCN
from recbole.model.context_aware_recommender.dcnv2 import DCNV2
from recbole.model.context_aware_recommender.deepfm import DeepFM
from recbole.model.context_aware_recommender.dssm import DSSM
from recbole.model.context_aware_recommender.ffm import FFM
from recbole.model.context_aware_recommender.fm import FM
from recbole.model.context_aware_recommender.fnn import FNN
from recbole.model.context_aware_recommender.fwfm import FwFM
from recbole.model.context_aware_recommender.lr import LR
from recbole.model.context_aware_recommender.nfm import NFM
from recbole.model.context_aware_recommender.pnn import PNN
from recbole.model.context_aware_recommender.widedeep import WideDeep
from recbole.model.context_aware_recommender.xdeepfm import xDeepFM
from recbole.model.context_aware_recommender.fignn import FiGNN
from recbole.model.context_aware_recommender.kd_dagfm import KD_DAGFM
from recbole.model.context_aware_recommender.eulernet import EulerNet
