from recbole.model.general_recommender.bpr import BPR
from recbole.model.general_recommender.convncf import ConvNCF
from recbole.model.general_recommender.dgcf import DGCF
from recbole.model.general_recommender.dmf import DMF
from recbole.model.general_recommender.fism import FISM
from recbole.model.general_recommender.gcmc import GCMC
from recbole.model.general_recommender.itemknn import ItemKNN
from recbole.model.general_recommender.lightgcn import LightGCN
from recbole.model.general_recommender.nais import NAIS
from recbole.model.general_recommender.neumf import NeuMF
from recbole.model.general_recommender.ngcf import NGCF
from recbole.model.general_recommender.pop import Pop
from recbole.model.general_recommender.spectralcf import SpectralCF
