# Dataset
convert_token_to_onehot: False  # (bool) Whether to convert token type features into one-hot form.
token_num_threhold: 10000       # (int) The threshold of one-hot conversion.

# Train
lgb_params:                     # (dict) Booster params.
    boosting: gbdt
    num_leaves: 90  
    min_data_in_leaf: 30
    max_depth: -1
    learning_rate: 0.1
    objective: binary
    lambda_l1: 0.1
    metric: ['auc', 'binary_logloss']
    force_row_wise: True
lgb_num_boost_round: 300        # (int) Number of boosting iterations.
