package:
  name: recbole
  version: 1.0.1

source:
  path: ../

requirements:
  build:
    - python
  host:
    - python
    - numpy >=1.17.2
    - scipy ==1.6.0
    - pandas >=1.0.5
    - tqdm >=4.48.2
    - pyyaml >=5.1.0
    - scikit-learn >=0.23.2
    - pytorch >=1.7.0
    - colorlog==4.7.2
    - colorama==0.4.4
    - tensorboard >=2.5.0
  run:
    - python
    - numpy >=1.17.2
    - scipy ==1.6.0
    - pandas >=1.0.5
    - tqdm >=4.48.2
    - pyyaml >=5.1.0
    - scikit-learn >=0.23.2
    - pytorch >=1.7.0
    - colorlog==4.7.2
    - colorama==0.4.4
    - tensorboard >=2.5.0
test:
  imports:
    - recbole

about:
  home: https://recbole.io/
  license: MIT
  summary: "A unified, comprehensive and efficient recommendation library"
  
